import type { AuditReport, AuditResult } from './types';

/**
 * Build Markdown report from audit results
 */
export function buildMarkdown(report: AuditReport): string {
  const sections: string[] = [];

  // Header
  sections.push('# Audit TAO - Detailed Report');
  sections.push('');

  // Timestamp
  sections.push(`**Generated**: ${new Date(report.timestamp).toLocaleString()}`);
  sections.push('');

  // Summary section
  sections.push('## 📊 Summary');
  sections.push('');
  sections.push('| Metric | Value |');
  sections.push('|--------|-------|');
  sections.push(`| Total Questions Audited | ${report.summary.total} |`);
  sections.push(`| Matched Pairs | ${report.summary.matched} |`);
  sections.push(`| Unmatched (Excel) | ${report.unmatched.excel.length} |`);
  sections.push(`| Unmatched (QTI) | ${report.unmatched.qti.length} |`);
  sections.push('');

  // Issues section
  sections.push('## ⚠️ Issues Found');
  sections.push('');
  sections.push('| Severity | Count | Status |');
  sections.push('|----------|-------|--------|');
  sections.push(`| 🔴 Bloquant (Critical) | **${report.summary.bloquants}** | ${report.summary.bloquants > 0 ? '❌ FAIL' : '✅ PASS'} |`);
  sections.push(`| 🟡 Majeur (Major) | **${report.summary.majeurs}** | ${report.summary.majeurs > 0 ? '⚠️ WARNING' : '✅ PASS'} |`);
  sections.push(`| 🔵 Mineur (Minor) | **${report.summary.mineurs}** | ℹ️ Info |`);
  sections.push('');

  // Critical Issues Detail
  const criticalResults = report.results.filter((r) => r.hasCriticalErrors);
  if (criticalResults.length > 0) {
    sections.push('## 🔴 Critical Issues (Must Fix)');
    sections.push('');
    criticalResults.forEach((result, idx) => {
      const qTitle = result.pair.qti.title || result.pair.qti.prompt.substring(0, 50);
      sections.push(`### Issue ${idx + 1}: ${qTitle}`);

      const bloquants = result.errors.filter((e) => e.severity === 'BLOQUANT');
      bloquants.forEach((error) => {
        sections.push(`- **${error.type}**: ${formatErrorDetail(error)}`);
      });
      sections.push('');
    });
  }

  // Major Issues Detail
  const majorResults = report.results.filter((r) => r.errors.some((e) => e.severity === 'MAJEUR'));
  if (majorResults.length > 0) {
    sections.push('## 🟡 Major Issues');
    sections.push('');
    majorResults.slice(0, 10).forEach((result, idx) => {
      const qTitle = result.pair.qti.title || result.pair.qti.prompt.substring(0, 50);
      sections.push(`- **Q${idx + 1}**: ${qTitle}`);

      const majeurs = result.errors.filter((e) => e.severity === 'MAJEUR');
      majeurs.forEach((error) => {
        sections.push(`  - ${error.type}: ${formatErrorDetail(error)}`);
      });
    });
    if (majorResults.length > 10) {
      sections.push(`\n... and ${majorResults.length - 10} more major issues`);
    }
    sections.push('');
  }

  // Unmatched Questions
  if (report.unmatched.excel.length > 0 || report.unmatched.qti.length > 0) {
    sections.push('## 📭 Unmatched Items');
    sections.push('');

    if (report.unmatched.excel.length > 0) {
      sections.push(`### Excel Questions Not Matched (${report.unmatched.excel.length})`);
      report.unmatched.excel.slice(0, 5).forEach((q, idx) => {
        sections.push(`${idx + 1}. Row ${q.metadata.excelRow}: "${q.prompt.substring(0, 60)}..."`);
      });
      if (report.unmatched.excel.length > 5) {
        sections.push(`... and ${report.unmatched.excel.length - 5} more`);
      }
      sections.push('');
    }

    if (report.unmatched.qti.length > 0) {
      sections.push(`### QTI Questions Not Matched (${report.unmatched.qti.length})`);
      report.unmatched.qti.slice(0, 5).forEach((q, idx) => {
        sections.push(`${idx + 1}. "${q.prompt.substring(0, 60)}..."`);
      });
      if (report.unmatched.qti.length > 5) {
        sections.push(`... and ${report.unmatched.qti.length - 5} more`);
      }
      sections.push('');
    }
  }

  // Recommendations
  sections.push('## 💡 Recommendations');
  sections.push('');
  if (report.summary.bloquants > 0) {
    sections.push('**ACTION REQUIRED**: Resolve all critical (Bloquant) issues before deployment.');
  } else if (report.summary.majeurs > 0) {
    sections.push('**RECOMMENDED**: Address major (Majeur) issues to ensure data quality.');
  } else {
    sections.push('✅ **All checks passed!** No critical issues detected.');
  }
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('*This report was automatically generated by TAO Audit.*');

  return sections.join('\n');
}

/**
 * Format error detail for display
 */
function formatErrorDetail(error: any): string {
  if (!error.detail) {
    return error.type;
  }

  const { detail } = error;

  if (detail.field === 'answer_count') {
    return `Expected ${detail.excel} answers, found ${detail.qti}`;
  }

  if (detail.field === 'correct_answers') {
    return `Found ${detail.qti} correct answer(s), expected 1`;
  }

  if (detail.field === 'correct_position') {
    return `Correct answer at position ${detail.qti}, expected position 0 (first)`;
  }

  if (detail.field === 'type') {
    return `Type mismatch: Excel="${detail.excel}", QTI="${detail.qti}"`;
  }

  if (detail.excel !== undefined && detail.qti !== undefined) {
    if (typeof detail.excel === 'string' && typeof detail.qti === 'string') {
      if (detail.excel.length < 60 && detail.qti.length < 60) {
        return `"${detail.excel}" ≠ "${detail.qti}"`;
      }
    }
    return `Excel: ${String(detail.excel).substring(0, 40)}... vs QTI: ${String(detail.qti).substring(0, 40)}...`;
  }

  return error.type;
}

/**
 * Build HTML report (for printing/viewing in browser)
 */
export function buildHTML(report: AuditReport): string {
  const markdown = buildMarkdown(report);

  // Simple HTML wrapper with basic styling
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TAO Audit Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 900px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    
    .container {
      background: white;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    
    h1, h2, h3 {
      margin-top: 1.5em;
      margin-bottom: 0.5em;
      color: #2c3e50;
    }
    
    h1 { border-bottom: 3px solid #3498db; padding-bottom: 0.5em; }
    h2 { border-bottom: 2px solid #ecf0f1; padding-bottom: 0.3em; }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1em 0;
    }
    
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    
    th {
      background: #f8f9fa;
      font-weight: 600;
      color: #2c3e50;
    }
    
    tr:hover {
      background: #f5f5f5;
    }
    
    code, pre {
      background: #f0f0f0;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
    }
    
    .critical { color: #e74c3c; font-weight: bold; }
    .warning { color: #f39c12; font-weight: bold; }
    .success { color: #27ae60; font-weight: bold; }
    
    @media print {
      body { background: white; }
      .container { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    ${markdown.split('\n').map((line) => {
      if (line.startsWith('###### ')) return `<h6>${line.substring(7)}</h6>`;
      if (line.startsWith('##### ')) return `<h5>${line.substring(6)}</h5>`;
      if (line.startsWith('#### ')) return `<h4>${line.substring(5)}</h4>`;
      if (line.startsWith('### ')) return `<h3>${line.substring(4)}</h3>`;
      if (line.startsWith('## ')) return `<h2>${line.substring(3)}</h2>`;
      if (line.startsWith('# ')) return `<h1>${line.substring(2)}</h1>`;
      if (line.startsWith('- ')) return `<li>${line.substring(2)}</li>`;
      if (line.trim() === '') return '<br>';
      return `<p>${line}</p>`;
    })}
  </div>
</body>
</html>`;

  return html;
}

/**
 * Export report as CSV (for spreadsheet analysis)
 */
export function buildCSV(report: AuditReport): string {
  const rows: string[] = [];

  // Header
  rows.push(
    'Type,Severity,Question Title,Question ID,Error Type,Detail,Excel Value,QTI Value'
  );

  // Results
  for (const result of report.results) {
    const title = result.pair.qti.title || result.pair.qti.prompt.substring(0, 50);
    const id = result.pair.qti.id || '';

    if (result.errors.length === 0) {
      rows.push(`Matched,OK,"${title}","${id}","No errors","","",`);
    } else {
      for (const error of result.errors) {
        const excelVal = error.detail?.excel ? String(error.detail.excel).substring(0, 50) : '';
        const qtiVal = error.detail?.qti ? String(error.detail.qti).substring(0, 50) : '';

        rows.push(
          `Comparison,${error.severity},"${title}","${id}","${error.type}","${error.detail?.field || ''}","${excelVal}","${qtiVal}"`
        );
      }
    }
  }

  // Unmatched
  for (const q of report.unmatched.excel) {
    rows.push(`Unmatched,BLOQUANT,"${q.prompt.substring(0, 50)}","","No match found in QTI","","",`);
  }

  for (const q of report.unmatched.qti) {
    rows.push(`Unmatched,INFO,"${q.prompt.substring(0, 50)}","${q.id || ''}","No match found in Excel","","",`);
  }

  return rows.join('\n');
}

/**
 * Download report as file
 */
export function downloadReport(
  report: AuditReport,
  format: 'json' | 'markdown' | 'html' | 'csv' = 'json'
): void {
  let content: string;
  let filename: string;
  let mimeType: string;

  switch (format) {
    case 'markdown':
      content = buildMarkdown(report);
      filename = `audit-report-${Date.now()}.md`;
      mimeType = 'text/markdown';
      break;
    case 'html':
      content = buildHTML(report);
      filename = `audit-report-${Date.now()}.html`;
      mimeType = 'text/html';
      break;
    case 'csv':
      content = buildCSV(report);
      filename = `audit-report-${Date.now()}.csv`;
      mimeType = 'text/csv';
      break;
    case 'json':
    default:
      content = JSON.stringify(report, null, 2);
      filename = `audit-report-${Date.now()}.json`;
      mimeType = 'application/json';
      break;
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
